import type { Campaign, GeographyData, TimeSeriesPoint, PlatformData, InsightItem, Brand } from './types'

export const brands: Brand[] = [
  { id: 'glow', name: 'Glow Essentials', products: ['Hydra Serum', 'Clarify Toner', 'Daily SPF'] },
  { id: 'nutri', name: 'NutriCore', products: ['Protein Blend', 'Greens Complex', 'Sleep Formula'] },
  { id: 'wander', name: 'Wanderlust', products: ['Travel Kit', 'Sun Collection'] },
]

export const campaigns: Campaign[] = [
  {
    id: 'c1',
    name: 'Spring Skincare Launch',
    brand: 'Glow Essentials',
    product: 'Hydra Serum',
    period: { start: 'Feb 1', end: 'Apr 15' },
    budget: 320000,
    spent: 287400,
    creators: 84,
    platforms: ['instagram', 'tiktok'],
    status: 'active',
    reach: 48200000,
    reachTarget: 42000000,
    er: 5.2,
    erTarget: 4.5,
    cpm: 5.96,
    impressions: 112000000,
    kpis: [
      { name: 'Reach', planned: 42000000, achieved: 48200000, unit: '', status: 'achieved' },
      { name: 'ER', planned: 4.5, achieved: 5.2, unit: '%', status: 'achieved' },
      { name: 'Posts', planned: 168, achieved: 162, unit: '', status: 'on-track' },
    ],
    geography: ['US', 'UK', 'CA', 'AU'],
  },
  {
    id: 'c2',
    name: 'Summer Travel Push',
    brand: 'Wanderlust',
    product: 'Sun Collection',
    period: { start: 'Mar 15', end: 'Jun 30' },
    budget: 210000,
    spent: 118500,
    creators: 52,
    platforms: ['instagram', 'youtube'],
    status: 'active',
    reach: 31600000,
    reachTarget: 38000000,
    er: 3.9,
    erTarget: 4.2,
    cpm: 3.75,
    impressions: 74000000,
    kpis: [
      { name: 'Reach', planned: 38000000, achieved: 31600000, unit: '', status: 'at-risk' },
      { name: 'ER', planned: 4.2, achieved: 3.9, unit: '%', status: 'at-risk' },
      { name: 'Posts', planned: 104, achieved: 58, unit: '', status: 'on-track' },
    ],
    geography: ['US', 'DE', 'FR', 'ES'],
  },
  {
    id: 'c3',
    name: 'Wellness Essentials Drop',
    brand: 'NutriCore',
    product: 'Greens Complex',
    period: { start: 'Jan 10', end: 'Feb 28' },
    budget: 155000,
    spent: 154820,
    creators: 41,
    platforms: ['instagram', 'tiktok', 'youtube'],
    status: 'completed',
    reach: 22800000,
    reachTarget: 20000000,
    er: 6.1,
    erTarget: 5.0,
    cpm: 6.79,
    impressions: 52000000,
    kpis: [
      { name: 'Reach', planned: 20000000, achieved: 22800000, unit: '', status: 'achieved' },
      { name: 'ER', planned: 5.0, achieved: 6.1, unit: '%', status: 'achieved' },
      { name: 'Posts', planned: 82, achieved: 86, unit: '', status: 'achieved' },
    ],
    geography: ['US', 'CA', 'AU'],
  },
  {
    id: 'c4',
    name: 'Back to Routine',
    brand: 'Glow Essentials',
    product: 'Daily SPF',
    period: { start: 'Mar 1', end: 'Apr 30' },
    budget: 98000,
    spent: 61200,
    creators: 29,
    platforms: ['instagram'],
    status: 'at-risk',
    reach: 9400000,
    reachTarget: 15000000,
    er: 2.8,
    erTarget: 4.0,
    cpm: 6.51,
    impressions: 19800000,
    kpis: [
      { name: 'Reach', planned: 15000000, achieved: 9400000, unit: '', status: 'below-target' },
      { name: 'ER', planned: 4.0, achieved: 2.8, unit: '%', status: 'below-target' },
      { name: 'Posts', planned: 58, achieved: 31, unit: '', status: 'on-track' },
    ],
    geography: ['US', 'UK'],
  },
  {
    id: 'c5',
    name: 'Holiday Gift Edit',
    brand: 'NutriCore',
    product: 'Sleep Formula',
    period: { start: 'May 1', end: 'Jun 30' },
    budget: 175000,
    spent: 0,
    creators: 0,
    platforms: ['instagram', 'tiktok', 'youtube'],
    status: 'planning',
    reach: 0,
    reachTarget: 28000000,
    er: 0,
    erTarget: 4.8,
    cpm: 0,
    impressions: 0,
    kpis: [
      { name: 'Reach', planned: 28000000, achieved: 0, unit: '', status: 'pending' },
      { name: 'ER', planned: 4.8, achieved: 0, unit: '%', status: 'pending' },
      { name: 'Posts', planned: 140, achieved: 0, unit: '', status: 'pending' },
    ],
    geography: ['US', 'UK', 'CA', 'DE', 'AU'],
  },
]

export const timeSeries: TimeSeriesPoint[] = [
  { month: 'Oct', reach: 18200000, spend: 68000, engagements: 940000 },
  { month: 'Nov', reach: 22400000, spend: 82000, engagements: 1120000 },
  { month: 'Dec', reach: 19800000, spend: 75000, engagements: 980000 },
  { month: 'Jan', reach: 26100000, spend: 94000, engagements: 1580000 },
  { month: 'Feb', reach: 41200000, spend: 148000, engagements: 2340000 },
  { month: 'Mar', reach: 54600000, spend: 184000, engagements: 3120000 },
]

export const platformData: PlatformData[] = [
  { platform: 'instagram', reach: 67400000, creators: 128, spend: 384000, er: 4.9 },
  { platform: 'tiktok', reach: 48200000, creators: 82, spend: 248000, er: 5.8 },
  { platform: 'youtube', reach: 16800000, creators: 37, spend: 90000, er: 3.4 },
]

export const geographyData: GeographyData[] = [
  { country: 'United States', code: 'US', reach: 74200000, er: 5.1, campaigns: 5, trend: 'up' },
  { country: 'United Kingdom', code: 'UK', reach: 21400000, er: 4.6, campaigns: 3, trend: 'up' },
  { country: 'Canada', code: 'CA', reach: 14800000, er: 4.2, campaigns: 3, trend: 'flat' },
  { country: 'Australia', code: 'AU', reach: 11200000, er: 5.4, campaigns: 3, trend: 'up' },
  { country: 'Germany', code: 'DE', reach: 8600000, er: 3.9, campaigns: 2, trend: 'down' },
  { country: 'France', code: 'FR', reach: 6200000, er: 3.7, campaigns: 1, trend: 'flat' },
]

export const insights: InsightItem[] = [
  {
    type: 'positive',
    label: 'Best performer',
    title: 'Spring Skincare Launch',
    value: '5.2% ER',
    note: 'Leading all active campaigns — 15% above target ER',
  },
  {
    type: 'warning',
    label: 'Needs attention',
    title: 'Back to Routine',
    value: '37% below reach target',
    note: 'Only 62% of creators have posted. Consider creator outreach.',
  },
  {
    type: 'positive',
    label: 'Strongest market',
    title: 'Australia',
    value: '5.4% avg ER',
    note: 'Highest engagement rate across all active geos',
  },
  {
    type: 'neutral',
    label: 'Most efficient platform',
    title: 'TikTok',
    value: '$5.14 CPM',
    note: '28% lower CPM than Instagram with higher avg ER',
  },
  {
    type: 'action',
    label: 'Optimization',
    title: 'Reallocate budget',
    value: '+$22K available',
    note: 'Spring Skincare is pacing under budget — consider boosting Back to Routine',
  },
]

export const summaryMetrics = {
  totalSpend: 621920,
  totalReach: 132000000,
  avgER: 4.8,
  totalCreators: 247,
  activeCampaigns: 3,
  prevTotalSpend: 554800,
  prevTotalReach: 115800000,
  prevAvgER: 5.1,
  prevCreators: 209,
  reachVsPlan: 0.14,
}
